version: 0.2

env:
  variables:
    S3_BUCKET: order101-frontend # 네 버킷 이름
    CLOUDFRONT_DISTRIBUTION_ID: EDTL5NOCRCLXW # 네 CloudFront 배포 ID

phases:
  install:
    commands:
      - echo "[install] we are in repo root, go to frontend"
      - cd frontend
      - npm install
  build:
    commands:
      - cd frontend
      - npm run build
  post_build:
    commands:
      - cd frontend
      - aws s3 sync dist/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
