version: 0.0
os: linux 

files:
  # target/ 폴더 전체를 복사 (와일드카드 미지원)
  - source: target/
    destination: /opt/synergy-backend/
  
  # scripts 폴더도 Artifact ZIP의 루트에서 바로 보입니다.
  - source: scripts/ 
    destination: /opt/synergy-backend/scripts/

permissions:
  - object: /opt/synergy-backend/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  # hooks 섹션의 location 경로도 'scripts/'로 시작합니다.
  ApplicationStop:
    - location: scripts/stop_app.sh 
      timeout: 60
      runas: ec2-user 

  AfterInstall:
    - location: scripts/chmod_jar.sh
      timeout: 60
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: ec2-user