version: 0.2

phases:
  install:
    commands:
      - echo 'Installing necessary dependencies...'
  build:
    commands:
      - echo 'Starting Maven package build...'
      - cd backend && mvn clean package -Dmaven.test.skip=true -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE
      - echo 'Build process complete.'
  post_build:
    commands:
      - echo 'Preparing artifacts for deployment...'
      - ls -la backend/target/*.jar

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/*
  base-directory: backend
  name: backend-deploy-artifact.zip