version: 0.2

phases:
  install:
    commands:
      - echo 'Installing necessary dependencies...'
  build:
    commands:
      - echo 'Starting Maven package build...'
      - cd backend
      - mvn clean package -Dmaven.test.skip=true -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE
      - echo 'Build process complete.'
  post_build:
    commands:
      - echo 'Preparing artifacts for deployment...'
      - cd backend
      - ARTIFACT_NAME=$(ls target/*.jar | head -n 1)
      - echo "Primary JAR file found - $ARTIFACT_NAME"

artifacts:
  files:
    - backend/target/*.jar
    - backend/appspec.yml
    - backend/scripts/*
  name: backend-deploy-artifact.zip