version: 0.2
phases:
  # install ë‹¨ê³„: í™˜ê²½ ë³€ìˆ˜ í™•ì¸ ìš©ë„ë¡œ ì ì ˆí•©ë‹ˆë‹¤.
  install:
    commands:
      - echo '--- INSTALL: Checking CodeBuild Environment ---'
      - echo "REPOSITORY_NAME: $REPOSITORY_NAME"
      - echo Preparing CodeBuild environment...

  pre_build:
    commands:
      - echo '--- PRE_BUILD: Logging in to Amazon ECR ---'
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
  build:
    commands:
      # ðŸš¨ 1. URIì™€ TAGëŠ” í•œ ë²ˆë§Œ ì •ì˜í•©ë‹ˆë‹¤.
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME 
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
      # ðŸš¨ 2. Docker build ëª…ë ¹ì€ í•œ ë²ˆë§Œ ì‹¤í–‰í•˜ë©°, -f ì˜µì…˜ì„ ì‚¬ìš©í•˜ì—¬ ê²½ë¡œë¥¼ ëª…í™•ížˆ ì§€ì •í•©ë‹ˆë‹¤.
      - echo '--- BUILD: Building Docker Image with backend/Dockerfile ---'
      - docker build -t $REPOSITORY_URI:latest -f backend/Dockerfile . 
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
      # ðŸš¨ 3. ECRì— ì´ë¯¸ì§€ í‘¸ì‹œë„ í•œ ë²ˆë§Œ ì‹¤í–‰í•©ë‹ˆë‹¤.
      - echo '--- BUILD: Pushing to ECR ---'
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # ECS ë°°í¬ë¥¼ ìœ„í•œ JSON íŒŒì¼ ìƒì„±
      - echo '--- POST_BUILD: Creating imagedefinitions.json for ECS deployment ---'
      - printf '[{"name":"synergy-order101-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json