version: 0.0
os: linux
files:
  - source: /
    destination: /opt/order101-ai

permissions:
  - object: /opt/order101-ai/scripts
    pattern: "*.sh"
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
